controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    front_right_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


front_right_leg_controller:
  ros__parameters:
    joints:
      - front_right_hip_joint
      - front_right_knee_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false
    open_loop_control: false

    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 1.0

      front_right_hip_joint:
        trajectory: 0.10
        goal: 0.05

      front_right_knee_joint:
        trajectory: 0.10
        goal: 0.05
